language: java

cache:
  directories:
  - $HOME/.m2

matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx

script: mvn install -B -V
